In [5]:
import pandas as pd 
import numpy as np

In [17]:
df_main = pd.read_csv(r'C:\Users\REBUILD\Downloads\Sleep_health_and_lifestyle_dataset.csv')

In [27]:
df_main.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [29]:
df_main.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [41]:
df_main['Occ'].unique()

array([nan, 'Sleep Apnea', 'Insomnia'], dtype=object)

# Descriptive Analysis

 What is the repartition of the data set by BMI ? (Pie Chart/Violion plot)

 What is the average duration of sleep by gender / age ? (Bar Chart)

 What is proportion of people having sleep disorder ? (Pie Chart)

 In average people who have a good score in 'quality of sleep' how many hours do they sleep ? (Box Plot)

 What are the top 5 'Occupation' who sleep the worst ? And the best ? (Horizontal Barchart)
 
 What is the averga eheartrate for a good sleeper and abad sleeper ? (Bar Chart)

### Relational Analysis 

It would interesting to investigiate a little bit more to find features influence more the quality of sleep 

So let's check that

Is there a correlation between Physical activity level and quality of sleep ? And with stress ? (Scatter Plot)


How does stress influence quality of sleep ? And the duration of sleep ? (Violin plot ? to show the distribution)

Does people with a higher heart rate sleep less/worst ? (Heatmap ?)

Does people how practice a physical activity sleep better/longer ? (Bar chart or heat map)

### By Group 

The quality of sleep by BMI

The quality of sleep by Occupation 

Duration of sleep by age